//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_asp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public string information { get; set; }
        public Nullable<int> sale { get; set; }
        public int category_id { get; set; }
        public string tag { get; set; }
        public string photo { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
